Dependency check plugin
finos/git-proxy pull request #799
Opened 2024-11-15 04:34 UTC by gonuguntlakavya

A plugin that uses dependency checker to check for the usage of vulnerable dependencies in git pushes. 
This PR is being submitted as part of citi finos hackathon

2026-02-01 05:47 UTC, jescalada requested changes
@gonuguntlakavya Thanks for the contribution!

Looks good so far, just a few comments on the implementation.

2026-02-01 05:47 UTC, jescalada commented on package.json
> +    "@finos/git-proxy-plugin-samples": "file:plugins/git-proxy-plugin-samples/finos-git-proxy-plugin-samples-0.1.0.tgz",
I don't think we should use references to the filesystem in package.json. As shown in the [plugin docs](https://git-proxy.finos.org/docs/development/plugins/), we can add the plugin filename to the `plugins` config instead.

2026-02-01 05:47 UTC, jescalada commented on config.schema.json
> +    "dependencyVulnThreshold": { "type": "string" },
This should be an entry within `plugins`, not a top-level config entry.

2026-02-01 05:47 UTC, jescalada commented on plugins/check-dependency-vulnerabilities/checkDependencyVuln.js
This should probably be moved to `plugins/git-proxy-sample-plugins` since we don't necessarily want to include it in the base GitProxy setup.

2026-02-01 05:47 UTC, jescalada commented on plugins/check-dependency-vulnerabilities/package.json
> +  "dependencies": {
`dependency-check` should be added to the plugin dependencies, rather than the parent repo since the library won't be used outside the plugin.

2026-02-01 05:47 UTC, jescalada commented on plugins/check-dependency-vulnerabilities/README.md
Would be great to run this through an LLM for fixing typos 👍🏼

2026-05-10 20:07 UTC, RichardUri commented
@jescalada Created a new PR with changes regarding the comments and clean up. Please review
#1529

2026-07-18 21:04 UTC, coopernetes commented
Closed in favour of #1529

2026-07-18 21:04 UTC, closed without merging